### Create a project
POST http://localhost:3000/api/v2/project
Authorization: Bearer {{manuscript_token}}
Accept: application/json
Content-Type: application/json


> {%
    client.assert(response.status === 200, "200 expected but received: " + response.status)
%}
